name: app1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.10
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  firebase_database: ^11.2.0
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo1.png
    - images/logo2.png
    - images/logo3.png
    - images/logo4.png
    - images/logo5.png